@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgyNTc2NDB9.0nKRZqTikA2cNsNSKrbKNOTytNhLRoBnlHPYShlCnTY

### PRODUCTS ###
### Product Index
GET http://localhost:3000/products
Authorization: Bearer {{jwt}}

### Product Show
GET http://localhost:3000/products/4

### Product Create
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Sr. Puff",
  "price": "90",
  "description": "Is a puffer fish"
}

### Product Update
PATCH http://localhost:3000/products/4
Content-Type: application/json

{
  "name": "Mr Hanky"
}

### Product Destroy
DELETE http://localhost:3000/products/7

### SUPPLIERS ###
### Supplier Index
GET http://localhost:3000/suppliers

### Supplier Show
GET http://localhost:3000/suppliers/3

### Supplier Create
POST http://localhost:3000/suppliers
Content-Type: application/json

{
  "name": "Ocean",
  "email": "fishtank@example.com",
  "phone_number": "414-fsh-tank"
}

### Supplier Update
PATCH http://localhost:3000/suppliers/3
Content-Type: application/json

{
  "name": "Ocean"
}

### Supplier Destroy
DELETE http://localhost:3000/suppliers/5

### IMAGES ###
### Image index
GET http://localhost:3000/images

### Image show
GET http://localhost:3000/images/3

### Image create
POST http://localhost:3000/images
Content-Type: application/json

{
  "url": "https://ih1.redbubble.net/image.2240276274.2643/mo,small,flatlay,product_square,600x600.jpg",
  "product_id": 2
}

### Image update
PATCH http://localhost:3000/images/8
Content-Type: application/json

{
  "product_id": 2
}

### Images delete
DELETE http://localhost:3000/images/8

### USERS ###
### Users index
GET http://localhost:3000/users

### Users create
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "test2",
  "email": "test2@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### SESSIONS ###
### Sessions Create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "password"
}

### ORDERS
### Order Index
GET http://localhost:3000/orders
Authorization: Bearer {{jwt}}

### Order Create
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "product_id": 1,
  "quantity": 3
}

### Order Show
GET http://localhost:3000/orders/1

### Carted Product ###
### Carted Product Index
GET http://localhost:3000/carted_products
Authorization: Bearer {{jwt}}

### Carted Product Create
POST http://localhost:3000/carted_products
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "product_id": 3,
  "quantity": 36,
  "status": "carted"
}